export const animals = {
  dolphin: {
    image: "/images/dolphin.jpg",
    facts: [
      "Dolphins have been shown to give distinct names to each other!",
      "Dolphins are known to display their own culture!",
      "Dolphins have two stomachs!",
      "Dolphins are highly intelligent and are often considered one of the most intelligent animals in the world.",
      'Dolphins have a unique method of hunting known as "herding" where they work together to surround and trap their prey.',
      "Dolphins have a layer of blubber under their skin that helps keep them warm in cold water.",
      "Dolphin ears are located on the sides of their head, and they use echolocation to navigate and communicate.",
      'Baby dolphins are called "calves" and are typically born weighing between 25-50 pounds.',
      'Some species of dolphins are known to live in groups of up to 100 individuals called "schools" or "pods".',
      "Dolphin teeth are cone-shaped and used for catching and holding onto their prey, but they do not chew their food.",
      "Some species of dolphins can live to be over 50 years old.",
      "Dolphins have a wide variety of vocalizations, including clicks, whistles, and other sounds that they use for communication.",
      "Dolphins are often considered to be playful animals, and they are known to engage in activities such as surfing and jumping out of the water for fun.",
    ],
  },
  lobster: {
    image: "/images/lobster.jpg",
    facts: [
      "Lobsters are invertebrates, meaning they do not have a backbone.",
      "Lobsters have a hard exoskeleton that they must shed and replace as they grow.",
      "Lobsters are carnivores and typically eat fish, mollusks, and other crustaceans.",
      "Lobsters have two large claws that they use for catching and crushing their food.",
      "Lobsters can live to be over 100 years old in some cases.",
      "Lobsters are considered a delicacy and are often served in fine dining restaurants.",
      "Lobsters have a complex nervous system and are capable of feeling pain.",
      "Lobsters can regenerate lost body parts, including their claws and legs.",
      "Lobsters are typically found in the ocean, but some species live in fresh water.",
      "Lobsters are an important part of the ocean ecosystem, serving as both predators and prey.",
    ],
  },
  starfish: {
    image: "/images/starfish.jpg",
    facts: [
      "Starfish, also known as sea stars, are not actually fish at all, but are echinoderms.",
      "Starfish have a unique ability to regenerate lost arms, and in some cases, can even regrow a new body from just a single arm.",
      "Starfish typically have five arms, but some species can have up to 40.",
      "Starfish do not have brains, but instead have a decentralized nervous system.",
      "Starfish have an amazing ability to adapt to a wide variety of environments, from shallow coral reefs to the deep sea.",
      "Starfish use their arms to move along the ocean floor, and some species can even swim.",
      "Starfish are carnivorous and feed on a variety of prey, including mollusks, crustaceans, and small fish.",
      "Starfish are important predators in the ocean and play a crucial role in maintaining the balance of marine ecosystems.",
      "Some species of starfish are toxic and can cause severe poisoning if eaten by humans.",
      "Starfish have been around for millions of years and are some of the oldest living animals on Earth.",
    ],
  },
};
